version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - sportal-network

  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/sportal
    networks:
      - sportal-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

networks:
  sportal-network:
    driver: bridge

volumes:
  mongodb_data: 